name: Latest blog post workflow
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add latest articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: ""
          commit_message: "Updated README with the latest articles"
          feed_list: "https://www.craftvalue.io/rss.xml"
          template: "$newline- [$title]($url?utm_campaign=github-profile&utm_source=github&utm_medium=posts-list)"
